CREATE WAREHOUSE IF NOT EXISTS SHARVIL_UTP_DASHBOARD
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

CREATE DATABASE IF NOT EXISTS SHARVIL_UTP_2026_DASHBOARD
  DATA_RETENTION_TIME_IN_DAYS = 1;

CREATE SCHEMA IF NOT EXISTS SHARVIL_UTP_2026_DASHBOARD.BRONZE;
CREATE SCHEMA IF NOT EXISTS SHARVIL_UTP_2026_DASHBOARD.SILVER;
CREATE SCHEMA IF NOT EXISTS SHARVIL_UTP_2026_DASHBOARD.GOLD;
CREATE SCHEMA IF NOT EXISTS SHARVIL_UTP_2026_DASHBOARD.REF;