CREATE WAREHOUSE IF NOT EXISTS UTP_DASHBOARD_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

CREATE DATABASE IF NOT EXISTS UTP_DASHBOARD
  DATA_RETENTION_TIME_IN_DAYS = 1;

CREATE SCHEMA IF NOT EXISTS UTP_DASHBOARD.BRONZE;
CREATE SCHEMA IF NOT EXISTS UTP_DASHBOARD.SILVER;
CREATE SCHEMA IF NOT EXISTS UTP_DASHBOARD.GOLD;
CREATE SCHEMA IF NOT EXISTS UTP_DASHBOARD.REF;