USE DATABASE UTP_DASHBOARD;
USE SCHEMA SILVER;
USE WAREHOUSE UTP_DASHBOARD_WH;

CREATE OR REPLACE VIEW UTP_DASHBOARD.SILVER.V_CHANGE_ORDERS_SILVER
COMMENT = 'View to clean and categorize the change orders data from bronze layer. It includes logic to group certain metrics, update district names using project details table and join with MPO reference table to get the correct MPO names and district abbreviations.' 
AS
WITH change_orders_init AS (
SELECT
    DISTRICT,
    CASE
        WHEN METRIC_NAME ILIKE '4_URBAN%' THEN '4_URBAN_CONNECTIVITY_ALL'
        WHEN METRIC_NAME ILIKE '11_BORDER%' THEN '11_RIDER_11($2.1B)'
        ELSE METRIC_NAME
    END AS METRIC_NAME,
    METRIC_VALUE
FROM BRONZE.CHANGE_ORDERS
),

co_2_group AS (
SELECT
    DISTRICT,
    '2_METRO/URBAN' AS METRIC_NAME,
    SUM(METRIC_VALUE) AS METRIC_VALUE
FROM change_orders_init
WHERE METRIC_NAME ILIKE '2%'
GROUP BY DISTRICT
),

co_10_group AS (
SELECT
    DISTRICT,
    '10_OTHER' AS METRIC_NAME,
    SUM(METRIC_VALUE) AS METRIC_VALUE
FROM change_orders_init
WHERE METRIC_NAME ILIKE '10_%' 
    AND NOT METRIC_NAME ILIKE ANY ('10_ADA', '10_FB', '10_GR', '10_LIA', '10_RGC', '10_RGS', '10_TPW', '10_Safety%', '10_Seaport%', '10_SCP', '10_ITD', '10_EAR')
GROUP BY DISTRICT
),

co_intermediate AS (
SELECT *
FROM change_orders_init
WHERE NOT METRIC_NAME ILIKE ANY ('2%') AND NOT (METRIC_NAME ILIKE '10_%' 
    AND NOT METRIC_NAME ILIKE ANY ('10_ADA', '10_FB', '10_GR', '10_LIA', '10_RGC', '10_RGS', '10_TPW', '10_Safety%', '10_Seaport%', '10_SCP', '10_ITD', '10_EAR'))
UNION ALL
SELECT *
FROM co_2_group
UNION ALL
SELECT *
FROM co_10_group
),

co_cat AS (
SELECT 
    DISTRICT,
    SPLIT_PART(METRIC_NAME, '_', 1) AS CATEGORY,
    METRIC_NAME,
    METRIC_VALUE
FROM co_intermediate
),

pd_dist_abbr AS (
    SELECT DISTINCT DISTRICT_DIVISION_ABBR, DISTRICT_DIVISION
    FROM SILVER.PROJECT_DETAILS_FILTERED_SILVER
),

co_updated_dist AS (
    SELECT
        co.*,
        pd.DISTRICT_DIVISION_ABBR
    FROM co_cat AS co
    LEFT JOIN pd_dist_abbr AS pd
    ON LOWER(TRIM(co.DISTRICT)) = LOWER(TRIM(pd.DISTRICT_DIVISION))
),
    
co_update_mpo AS (
SELECT
    co.DISTRICT,
    CASE
        WHEN co.DISTRICT_DIVISION_ABBR IS NULL THEN mpo.district_abbr
        ELSE co.DISTRICT_DIVISION_ABBR
    END AS DISTRICT_DIVISION_ABBR,
    CASE
        WHEN co.DISTRICT = mpo.change_orders_mpo AND mpo.change_orders_mpo != '' THEN mpo.mpo_short
        WHEN co.DISTRICT = '[BMT] JHORTS MPO' THEN 'HGAC MPO'
        ELSE INITCAP(co.DISTRICT, '')
    END AS DISTRICT_MPO_NEW,
    co.CATEGORY,
    co.METRIC_NAME,
    co.METRIC_VALUE
FROM co_updated_dist AS co
LEFT JOIN REF.MPO_REFERENCE AS mpo
ON co.DISTRICT = mpo.change_orders_mpo
),

change_orders_final AS (
    SELECT
        CASE
            WHEN DISTRICT = '[BMT] JHORTS MPO' THEN 'HOU/BMT'
            ELSE DISTRICT_DIVISION_ABBR
        END AS DISTRICT_DIVISION_ABBR,
        DISTRICT,
        DISTRICT_MPO_NEW,
        CASE
            WHEN CATEGORY = '4' AND METRIC_NAME ILIKE '4_U%' THEN '4U'
            WHEN CATEGORY = '4' AND METRIC_NAME ILIKE '4_R%' THEN '4R'
            WHEN CATEGORY = '8' AND METRIC_NAME ILIKE '8_Safety' THEN '8SF'
            WHEN CATEGORY = '8' AND METRIC_NAME ILIKE '8%Rail' THEN '8RX'
            WHEN CATEGORY = '11' AND METRIC_NAME ILIKE '11_DISTRICT_SAF%' THEN '11SF'
            WHEN CATEGORY = '11' AND METRIC_NAME ILIKE '11_PES' THEN '11ES' 
            WHEN CATEGORY = '11' AND METRIC_NAME ILIKE '11_DISTRICT_Dis%' THEN '11DD'
            WHEN CATEGORY = '11' AND METRIC_NAME ILIKE '11_RI%' THEN '11B'
            WHEN CATEGORY = '11' AND METRIC_NAME ILIKE '11_CO%' THEN '11CO'
            WHEN CATEGORY = '10' AND METRIC_NAME ILIKE '10_ADA' THEN '10ADA'
            WHEN CATEGORY = '10' AND METRIC_NAME ILIKE '10_FB' THEN '10FB'
            WHEN CATEGORY = '10' AND METRIC_NAME ILIKE '10_GR' THEN '10GR'
            WHEN CATEGORY = '10' AND METRIC_NAME ILIKE '10_LIA' THEN '10LIA'
            WHEN CATEGORY = '10' AND METRIC_NAME ILIKE '10_RGC' THEN '10RGC'
            WHEN CATEGORY = '10' AND METRIC_NAME ILIKE '10_RGS' THEN '10RGS'
            WHEN CATEGORY = '10' AND METRIC_NAME ILIKE '10_TPW' THEN '10TPW'
            WHEN CATEGORY = '10' AND METRIC_NAME ILIKE '10_Safety%' THEN '10SRATP'
            WHEN CATEGORY = '10' AND METRIC_NAME ILIKE ANY ('10_SCP', '10_Seaport%') THEN '10SCP'
            WHEN CATEGORY = '10' AND METRIC_NAME ILIKE '10_ITD' THEN '10ITD'
            WHEN CATEGORY = '10' AND METRIC_NAME ILIKE '10_EAR' THEN '10EAR'
            WHEN CATEGORY = '10' AND NOT METRIC_NAME ILIKE ANY ('10_ADA', '10_FB', '10_GAR', '10_LIA', '10_RGC', '10_RGS', '10_TPW', '10_Safety%', '10_Seaport%', '10_SCP', '10_ITD', '10_EAR') THEN '10OTHER'
            ELSE CATEGORY
        END AS CATEGORY_NEW,
        METRIC_NAME,
        CASE
            WHEN METRIC_NAME ILIKE '9_TAP_F%' THEN 'Transportation Alternatives Flex Program'
            WHEN METRIC_NAME ILIKE '9_TAP_ST%' THEN 'Transportation Alternatives Program - Non-TMAs'
            WHEN METRIC_NAME ILIKE '6_%' THEN 'Bridge Division'
            ELSE CONCAT(DISTRICT_DIVISION_ABBR, ' - ', DISTRICT_MPO_NEW)
        END AS District_MPO_Division,
        METRIC_VALUE
    FROM co_update_mpo
    WHERE CATEGORY != '3' -- Exclude category 3 as per the requirement
)

SELECT DISTINCT
    DISTRICT,
    CASE
        WHEN DISTRICT = '[BMT] JHORTS MPO' THEN 'HOU/BMT - HGAC MPO'
        ELSE District_MPO_Division
    END AS District_MPO_Division,
    CATEGORY_NEW AS CATEGORY,
    METRIC_NAME,
    METRIC_VALUE AS CHANGE_ORDERS_AMOUNT
FROM change_orders_final
;