USE DATABASE UTP_DASHBOARD;
USE WAREHOUSE UTP_DASHBOARD_WH;
USE SCHEMA REF;

CREATE OR REPLACE VIEW REF.V_CATEGORY_MAP_CURRENT 
COMMENT = 'A copy of category map table having records that are currently valid/active.'
AS
SELECT *
    EXCLUDE(valid_to)
FROM REF.CATEGORY_MAP
WHERE is_active = TRUE AND valid_to IS NULL;
