USE ROLE SYSADMIN;
USE DATABASE SHARVIL_UTP_2026_DASHBOARD;
USE SCHEMA BRONZE;

CREATE OR REPLACE FILE FORMAT BRONZE.CHANGE_ORDERS_CSV_FF
  TYPE = CSV
  -- SKIP_HEADER = 1 -- No need to skip if we use PARSE_HEADER = TRUE
  PARSE_HEADER = TRUE
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  TRIM_SPACE = TRUE
  NULL_IF = ('', 'NULL', 'null')
  ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
  REPLACE_INVALID_CHARACTERS = TRUE
  -- If you suspect smart quotes / Windows-1252 like LET_DATA:
  -- ENCODING = 'WINDOWS1252'
;
