USE ROLE SYSADMIN;
USE DATABASE SHARVIL_UTP_2026_DASHBOARD;
USE SCHEMA BRONZE;

CREATE OR REPLACE FILE FORMAT BRONZE.LET_DATA_CSV_FF
  TYPE = CSV
  SKIP_HEADER = 1
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  TRIM_SPACE = TRUE
  NULL_IF = ('', 'NULL', 'null')
  ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
  ENCODING = 'WINDOWS1252'
  REPLACE_INVALID_CHARACTERS = TRUE
  TIMESTAMP_FORMAT = 'MM/DD/YYYY HH24:MI';
