USE ROLE SYSADMIN;
USE DATABASE SHARVIL_UTP_2026_DASHBOARD;
USE SCHEMA BRONZE;

CREATE OR REPLACE FILE FORMAT BRONZE.CARRYOVERS_CSV_FF
  TYPE = CSV
  SKIP_HEADER = 1
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  NULL_IF = ('', 'NULL');

ALTER FILE FORMAT BRONZE.CARRYOVERS_CSV_FF 
SET ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE;