USE ROLE SYSADMIN;
USE DATABASE SHARVIL_UTP_2026_DASHBOARD;
USE SCHEMA BRONZE;
USE WAREHOUSE SHARVIL_UTP_DASHBOARD;

CREATE OR REPLACE TABLE BRONZE.LET_DATA (
    LET_YEAR                             NUMBER(4,0),
    DISTRICT                             VARCHAR,
    CATEGORY                             VARCHAR,
    ANALYSIS_REPORT_DESCRIPTION          VARCHAR,
    FUNDING_AMOUNT                       FLOAT,
    CAT_SERIES                           FLOAT,
    APPN_CODE                            VARCHAR,
    CCSJ                                 VARCHAR,
    CSJ                                  VARCHAR,
    DISTRICT_LET_DATE                    DATE,
    LETTING_CODE                         VARCHAR,
    APPROVED_LET_DATE                    DATE,
    ACTUAL_LET_DATE                      DATE,
    EST_LOWBID                           FLOAT,
    PROJECT_NUMBER                       VARCHAR,
    PID                                  VARCHAR,
    FIXED_FLAG                           VARCHAR,
    FED_PCT                              FLOAT,
    STATE_PCT                            FLOAT,
    LOCAL_PCT                            FLOAT,
    FEDERAL_AMOUNT                       FLOAT,
    STATE_AMOUNT                         FLOAT,
    LOCAL_AMOUNT                         FLOAT,
    LET_DATE                             DATE,
    MPO_CD_DSCR                          VARCHAR,
    COUNTY                               VARCHAR,
    WORK_PROGRAM                         VARCHAR,
    UTP_AUTHORITY                        VARCHAR,
    PROJECT_DESCRIPTION                  VARCHAR,
    HIGHWAY                              VARCHAR,
    ROW_CSJ                              VARCHAR,
    TOLL_FLAG                            VARCHAR,
    FUNC_CLASS                           INTEGER,
    PROJECT_CLASS                        VARCHAR,
    NHS_FLAG                             VARCHAR,
    COMMENTS                             VARCHAR,
    STATE_SOURCE                         VARCHAR,
    EST_COST                             FLOAT,
    CDA_CODE                             VARCHAR,
    FUNDING_LINE_NO                      INTEGER,
    LIMIT_FROM                           VARCHAR,
    LIMIT_TO                             VARCHAR,
    APPL_PCT                             FLOAT,
    FPAA                                 VARCHAR,
    BID_RECEIVED_UNTIL_DATE              DATE,
    PLANNED_LET_DATE                     DATE,
    FUNDS_SUBGROUPLING                   VARCHAR,
    FUND_GROUPING                        VARCHAR,
    LET_TYPE_DESCRIPTION                 VARCHAR,
    MNTE_ORDR_DT                         DATE,
    MNTE_ORDR_NBR                        VARCHAR,
    NEPA_CLEAR_DT                        DATE,
    PROJ_CLASS_DSCR                      VARCHAR,
    PROJECT_ID                           VARCHAR,
    PROJ_CNTY_1                          VARCHAR,
    PROJ_STAGE                           VARCHAR,
    PROJECT_SUBTYPE                      VARCHAR,
    PROJ_TYPE                            VARCHAR,
    ROW_PROJECT_ID                       VARCHAR,
    SEAL_FLAG                            VARCHAR,
    SHORT_DESCRIPTION                    VARCHAR,
    TIMESTAMP                            TIMESTAMP_NTZ,
    TDC                                  VARCHAR,
    TDC_PCT                              INTEGER,
    INGESTED_AT                          TIMESTAMP_NTZ
)
COMMENT = 'Initialize the current analysis details (LET) table to load data from the new current analysis details file each week.';
